# config.py
# Назначение: конфиги из ENV/CLI + дефолты
# TODO:
# - API_BASE_URL, TIMEOUT, RETRIES, BACKOFF
# - DATE_FROM/DATE_TO
# - пути: RAW_DIR, CURATED_DIR, TMP_DIR, DQ_DIR
# - CHUNK_SIZE_BYTES, MAX_PARALLEL_DATES, SCHEMA_VERSION
