columns:
  - name: Date/Time
    type: Datetime
    required: True
  - name: Lat
    type: float
    required: True
  - name: Lon
    type: float
    required: True
  - name: Base
    type: str
    required: True

type_columns:
  - Date/Time: datetime
  - Lat: float
  - Lon: float
  - Base: str